@host=https://localhost:7160

POST  {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Georgijs",
    "lastName":"Katasevs",
    "email":"geokat@jumjum.com",
    "password":"qwerty1234"
}